### ISSUE TITLE
关于episode划分

### ISSUE THREAD

**Issue by RobbieOvO** [yankun-pku/Inferring-Prototypes-for-Multi-Label-Few-Shot-Image-Classification-with-Word-Vector-Guided-Attention#1]
作者你好，目前我也在进行多标签少样本的研究。

文章中有一点小疑惑，
关于LaSO的设置，我看他公开的源码中10个episodes没有query和support set的划分，请问在你使用LaSO设置进行自己模型的实验的时候episode是如何设置的呢？

希望得到回复，谢谢。

**Comment by myt889** [comment]
您好，这篇文章开源代码在哪里？可以发个链接么？非常感谢！

**Comment by myt889** [comment]
> 作者你好，目前我也在进行多标签少样本的研究。
> 
> 文章中有一点小疑惑， 关于LaSO的设置，我看他公开的源码中10个episodes没有query和support set的划分，请问在你使用LaSO设置进行自己模型的实验的时候episode是如何设置的呢？
> 
> 希望得到回复，谢谢。

您好，这篇文章开源代码在哪里？可以发个链接么？非常感谢！

**Comment by RobbieOvO** [comment]
> > 作者你好，目前我也在进行多标签少样本的研究。
> > 文章中有一点小疑惑， 关于LaSO的设置，我看他公开的源码中10个episodes没有query和support set的划分，请问在你使用LaSO设置进行自己模型的实验的时候episode是如何设置的呢？
> > 希望得到回复，谢谢。
> 
> 您好，这篇文章开源代码在哪里？可以发个链接么？非常感谢！

你好，我没有找到这篇文章的开源代码，是自己实现的方法。提到的数据集划分是LaSO的划分方法，可以查看LaSO的论文给了链接。

**Comment by yankun-pku** [comment]
你好，因为目前的训练框架是基于SenseTime的公司框架，还没发开源。
